### ISSUE TITLE
failed to find Asset Entry

### ISSUE THREAD

**Issue by tw1st31337** [FMTDev/FMT.Releases#34]
editor crashes when extracting a modified file from a .fifamod file.

![image](https://github.com/user-attachments/assets/74407045-d760-4d53-9706-4f44668067c5)

**Comment by tw1st31337** [comment]
btw heres an additional log

```
[30.11.2024 16:30:06]: FMT:OnStartup 
[11/30/2024 4:30:06 PM]: FMT:OnStartup:Complete 
[11/30/2024 4:30:30 PM]: Loaded Plugin: E:\Games\FMT-25.10.9094.18717\FMT\Plugins\FC25Plugin.dll. 
[11/30/2024 4:31:12 PM]: Unable to find the ChunkAssetEntry for core/chunkfiles/cfc_additional_data 
[11/30/2024 4:36:56 PM]: System.Exception: Failed to find Asset Entry
   at FrostySdk.Managers.AssetManager.GetAsset(AssetEntry entry, Boolean getModified)
   at FrostySdk.Managers.AssetManager.GetChunk(ChunkAssetEntry entry)
   at FC25Plugin.Textures.FC25TextureResourceReader.ReadInStream(NativeReader nativeReader, Texture texture)
   at FrostySdk.Resources.Texture.ReadInStream(NativeReader nativeReader)
   at FrostySdk.Resources.Texture.ReadInResourceAsset(ResAssetEntry resAssetEntry)
   at FrostySdk.Resources.Texture..ctor(Stream stream, ResAssetEntry resAssetEntry)
   at FMT.Controls.SharedFunctions.ExportingService.ExportAsset(IAssetEntry assetEntry, String saveLocation, IAssetEntry skeletonEntry)
   at FMT.Controls.SharedFunctions.ExportingService.ExportTextureAssetUsingDialog(EbxAssetEntry ebxAssetEntry)
   at FMT.Controls.SharedFunctions.ExportingService.Export(IAssetEntry asset)
   at FMT.Pages.Common.OpenedFile.btnExport_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at FMT.App.Main() 
```

**Comment by tw1st31337** [comment]
> Hi there. I have seen this before. I had to delete the cache, repair (possibly reinstall) the game to fix it. If that hasn't worked, perhaps its something I've got wrong with fifamod. What mod are you trying to open? Can you supply it?

i may be retarded as i am trying to open a fifa 22 mod on fc 25 mod editor (which is probably causing the error) but yes i can

https://dl.fifa-infinity.com/fifa-22/retro-bootpack-and-ballpack/
